2023-09-22 08:28:39,871 - INFO - autoreload - autoreload.py - Watching for file changes with StatReloader
2023-09-22 08:29:00,560 - INFO - autoreload - autoreload.py - C:\Users\user\PycharmProjects\django_hw\mysite\mysite\settings.py changed, reloading.
2023-09-22 08:29:01,071 - INFO - autoreload - autoreload.py - Watching for file changes with StatReloader
2023-09-22 08:29:37,437 - INFO - autoreload - autoreload.py - C:\Users\user\PycharmProjects\django_hw\mysite\hw\views.py changed, reloading.
2023-09-22 08:29:38,055 - INFO - autoreload - autoreload.py - Watching for file changes with StatReloader
2023-09-22 08:30:48,648 - INFO - autoreload - autoreload.py - C:\Users\user\PycharmProjects\django_hw\mysite\hw\views.py changed, reloading.
2023-09-22 08:30:49,334 - INFO - autoreload - autoreload.py - Watching for file changes with StatReloader
2023-09-22 08:31:30,203 - INFO - autoreload - autoreload.py - C:\Users\user\PycharmProjects\django_hw\mysite\hw\views.py changed, reloading.
2023-09-22 08:31:30,812 - INFO - autoreload - autoreload.py - Watching for file changes with StatReloader
2023-09-22 08:32:12,392 - INFO - autoreload - autoreload.py - C:\Users\user\PycharmProjects\django_hw\mysite\hw\views.py changed, reloading.
2023-09-22 08:32:13,126 - INFO - autoreload - autoreload.py - Watching for file changes with StatReloader
2023-09-22 08:32:31,050 - INFO - views - views.py - User Alex Went to the main page about me
2023-09-22 08:32:31,054 - INFO - basehttp - basehttp.py - "GET /hw/about_me HTTP/1.1" 200 305
2023-09-29 07:54:44,883 - INFO - autoreload - autoreload.py - Watching for file changes with StatReloader
2023-09-29 07:54:49,848 - INFO - basehttp - basehttp.py - "GET /admin/ing/request/ HTTP/1.1" 302 0
2023-09-29 07:54:50,061 - INFO - basehttp - basehttp.py - "GET /admin/login/?next=/admin/ing/request/ HTTP/1.1" 200 4205
2023-09-29 07:54:50,168 - INFO - basehttp - basehttp.py - "GET /static/admin/css/login.css HTTP/1.1" 200 958
2023-09-29 07:54:56,509 - WARNING - log - log.py - Not Found: /
2023-09-29 07:54:56,509 - WARNING - basehttp - basehttp.py - "GET / HTTP/1.1" 404 2162
2023-09-29 07:55:03,466 - INFO - basehttp - basehttp.py - "GET /hw HTTP/1.1" 301 0
2023-09-29 07:55:03,469 - INFO - views - views.py - User Alex I went to the main page
2023-09-29 07:55:03,702 - ERROR - log - log.py - Internal Server Error: /hw/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\django_hw\mysite\hw\views.py", line 10, in index
    return render(request, 'hw/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
2023-09-29 07:55:03,712 - ERROR - basehttp - basehttp.py - "GET /hw/ HTTP/1.1" 500 129165
2023-09-29 07:56:58,835 - INFO - autoreload - autoreload.py - C:\Users\user\PycharmProjects\django_hw\mysite\mysite\settings.py changed, reloading.
2023-09-29 07:56:59,567 - INFO - autoreload - autoreload.py - Watching for file changes with StatReloader
2023-09-29 07:58:28,745 - INFO - views - views.py - User Alex I went to the main page
2023-09-29 07:58:28,751 - INFO - basehttp - basehttp.py - "GET /hw/ HTTP/1.1" 200 219
2023-09-29 07:59:41,322 - INFO - autoreload - autoreload.py - C:\Users\user\PycharmProjects\django_hw\mysite\hw\views.py changed, reloading.
2023-09-29 07:59:41,974 - INFO - autoreload - autoreload.py - Watching for file changes with StatReloader
2023-09-29 07:59:54,776 - INFO - autoreload - autoreload.py - C:\Users\user\PycharmProjects\django_hw\mysite\hw\views.py changed, reloading.
2023-09-29 07:59:55,351 - INFO - autoreload - autoreload.py - Watching for file changes with StatReloader
2023-09-29 08:00:21,446 - INFO - autoreload - autoreload.py - C:\Users\user\PycharmProjects\django_hw\mysite\hw\views.py changed, reloading.
2023-09-29 08:00:22,021 - INFO - autoreload - autoreload.py - Watching for file changes with StatReloader
2023-09-29 08:00:54,582 - INFO - autoreload - autoreload.py - C:\Users\user\PycharmProjects\django_hw\mysite\hw\admin.py changed, reloading.
2023-09-29 08:00:55,763 - INFO - autoreload - autoreload.py - Watching for file changes with StatReloader
2023-09-29 08:01:53,035 - INFO - autoreload - autoreload.py - Watching for file changes with StatReloader
2023-09-29 08:01:58,975 - INFO - basehttp - basehttp.py - "GET /admin/ HTTP/1.1" 302 0
2023-09-29 08:01:59,029 - INFO - basehttp - basehttp.py - "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4181
2023-09-29 08:02:02,576 - INFO - basehttp - basehttp.py - "GET /admin/ HTTP/1.1" 302 0
2023-09-29 08:02:02,583 - INFO - basehttp - basehttp.py - "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4181
2023-09-29 08:02:04,504 - INFO - basehttp - basehttp.py - "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
2023-09-29 08:02:04,547 - INFO - basehttp - basehttp.py - "GET /admin/ HTTP/1.1" 200 6173
2023-09-29 08:02:08,160 - INFO - basehttp - basehttp.py - "GET /admin/hw/order/add/ HTTP/1.1" 200 9837
2023-09-29 08:02:08,267 - INFO - basehttp - basehttp.py - "GET /admin/jsi18n/ HTTP/1.1" 200 3343
2023-09-29 08:02:48,363 - INFO - autoreload - autoreload.py - C:\Users\user\PycharmProjects\django_hw\mysite\hw\admin.py changed, reloading.
2023-09-29 08:02:49,055 - INFO - autoreload - autoreload.py - Watching for file changes with StatReloader
2023-09-29 08:03:29,309 - INFO - autoreload - autoreload.py - C:\Users\user\PycharmProjects\django_hw\mysite\hw\admin.py changed, reloading.
2023-09-29 08:03:29,856 - INFO - autoreload - autoreload.py - Watching for file changes with StatReloader
2023-09-29 08:03:31,203 - INFO - basehttp - basehttp.py - "GET /admin/hw/order/add/ HTTP/1.1" 200 11499
2023-09-29 08:03:31,248 - INFO - basehttp - basehttp.py - "GET /admin/jsi18n/ HTTP/1.1" 200 3343
2023-09-29 08:03:31,338 - INFO - basehttp - basehttp.py - "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
2023-09-29 08:03:37,504 - INFO - basehttp - basehttp.py - "GET /admin/hw/client/add/ HTTP/1.1" 200 10647
2023-09-29 08:03:37,515 - INFO - basehttp - basehttp.py - "GET /admin/jsi18n/ HTTP/1.1" 200 3343
2023-09-29 08:03:46,234 - INFO - basehttp - basehttp.py - "POST /admin/hw/client/add/ HTTP/1.1" 302 0
2023-09-29 08:03:46,318 - INFO - basehttp - basehttp.py - "GET /admin/hw/client/ HTTP/1.1" 200 9303
2023-09-29 08:03:46,330 - INFO - basehttp - basehttp.py - "GET /admin/jsi18n/ HTTP/1.1" 200 3343
2023-09-29 08:03:50,008 - INFO - basehttp - basehttp.py - "GET /admin/hw/order/ HTTP/1.1" 200 7964
2023-09-29 08:03:50,019 - INFO - basehttp - basehttp.py - "GET /admin/jsi18n/ HTTP/1.1" 200 3343
2023-09-29 08:03:51,426 - INFO - basehttp - basehttp.py - "GET /admin/hw/order/add/ HTTP/1.1" 200 11534
2023-09-29 08:03:51,437 - INFO - basehttp - basehttp.py - "GET /admin/jsi18n/ HTTP/1.1" 200 3343
2023-09-29 08:03:55,808 - INFO - basehttp - basehttp.py - "GET /admin/hw/product/add/?_to_field=id&_popup=1 HTTP/1.1" 200 6306
2023-09-29 08:03:55,821 - INFO - basehttp - basehttp.py - "GET /admin/jsi18n/ HTTP/1.1" 200 3343
2023-09-29 08:04:09,153 - INFO - basehttp - basehttp.py - "GET /admin/hw/product/add/ HTTP/1.1" 200 10648
2023-09-29 08:04:09,164 - INFO - basehttp - basehttp.py - "GET /admin/jsi18n/ HTTP/1.1" 200 3343
2023-09-29 08:05:15,889 - INFO - autoreload - autoreload.py - C:\Users\user\PycharmProjects\django_hw\mysite\hw\views.py changed, reloading.
2023-09-29 08:05:16,553 - INFO - autoreload - autoreload.py - Watching for file changes with StatReloader
2023-09-29 08:05:24,535 - ERROR - log - log.py - Internal Server Error: /hw/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\django_hw\mysite\hw\views.py", line 14, in index
    orders_7_days = Order.objects.filter(date__gte=now - timedelta(days=7))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date' into field. Choices are: client, client_id, id, products, registration_date, total_cost
2023-09-29 08:05:24,542 - ERROR - basehttp - basehttp.py - "GET /hw/ HTTP/1.1" 500 109866
2023-10-03 08:59:28,188 - INFO - autoreload - autoreload.py - Watching for file changes with StatReloader
2023-10-03 09:00:32,299 - INFO - autoreload - autoreload.py - Watching for file changes with StatReloader
2023-10-03 09:02:34,377 - INFO - autoreload - autoreload.py - Watching for file changes with StatReloader
2023-10-03 09:02:37,089 - WARNING - log - log.py - Not Found: /
2023-10-03 09:02:37,090 - WARNING - basehttp - basehttp.py - "GET / HTTP/1.1" 404 2162
2023-10-03 09:03:16,563 - INFO - autoreload - autoreload.py - C:\Users\user\PycharmProjects\django_hw\mysite\hw\urls.py changed, reloading.
2023-10-03 09:03:17,270 - INFO - autoreload - autoreload.py - Watching for file changes with StatReloader
2023-10-03 09:03:19,079 - WARNING - log - log.py - Not Found: /add_photo
2023-10-03 09:03:19,080 - WARNING - basehttp - basehttp.py - "GET /add_photo HTTP/1.1" 404 2207
2023-10-03 09:04:05,935 - INFO - basehttp - basehttp.py - "GET /hw/add_photo HTTP/1.1" 200 1869
2023-10-03 09:04:30,607 - INFO - autoreload - autoreload.py - C:\Users\user\PycharmProjects\django_hw\mysite\hw\views.py changed, reloading.
2023-10-03 09:04:31,252 - INFO - autoreload - autoreload.py - Watching for file changes with StatReloader
2023-10-03 09:05:27,285 - INFO - autoreload - autoreload.py - C:\Users\user\PycharmProjects\django_hw\mysite\hw\views.py changed, reloading.
2023-10-03 09:05:27,981 - INFO - autoreload - autoreload.py - Watching for file changes with StatReloader
2023-10-03 10:01:11,442 - INFO - autoreload - autoreload.py - Watching for file changes with StatReloader
2023-10-03 10:01:13,726 - WARNING - log - log.py - Not Found: /
2023-10-03 10:01:13,726 - WARNING - basehttp - basehttp.py - "GET / HTTP/1.1" 404 2162
2023-10-03 10:01:21,058 - INFO - basehttp - basehttp.py - "GET /hw/add_photo HTTP/1.1" 200 2084
2023-10-03 10:02:33,884 - INFO - autoreload - autoreload.py - C:\Users\user\PycharmProjects\django_hw\mysite\hw\views.py changed, reloading.
2023-10-03 10:02:34,629 - INFO - autoreload - autoreload.py - Watching for file changes with StatReloader
